import 'package:flutter/material.dart';

import '../../../app/theme.dart';

class DownloadArchiveDialog extends StatefulWidget {
  const DownloadArchiveDialog({super.key});

  @override
  State<DownloadArchiveDialog> createState() => _DownloadArchiveDialogState();
}

class _DownloadArchiveDialogState extends State<DownloadArchiveDialog> {
  String _archive = 'Weekly Full System Snapshot - 2026-10-24_0400';
  String _format = 'ZIP';
  bool _encrypt = false;

  @override
  Widget build(BuildContext context) {
    return Dialog(
      insetPadding: const EdgeInsets.symmetric(horizontal: 20, vertical: 24),
      clipBehavior: Clip.antiAlias,
      shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(modalRadius)),
      child: ConstrainedBox(
        constraints: BoxConstraints(
          maxWidth: 520,
          maxHeight: MediaQuery.sizeOf(context).height * .9,
        ),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Container(
              height: modalChromeHeight,
              padding: const EdgeInsets.fromLTRB(12, 6, 6, 6),
              decoration: modalHeaderDecoration,
              child: Row(
                children: [
                  const Expanded(
                    child: Text('Download Archive',
                        style: TextStyle(
                            fontSize: 18, fontWeight: FontWeight.w800)),
                  ),
                  IconButton(
                    tooltip: 'Close',
                    onPressed: () => Navigator.of(context).pop(),
                    icon: const Icon(Icons.close_rounded),
                  ),
                ],
              ),
            ),
            Flexible(
              child: SingleChildScrollView(
                padding: const EdgeInsets.all(12),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Text('Select Backup Archive',
                        style: TextStyle(
                            fontSize: 11, fontWeight: FontWeight.w800)),
                    const SizedBox(height: 6),
                    DropdownButtonFormField<String>(
                      value: _archive,
                      decoration: const InputDecoration(filled: true),
                      items: const [
                        'Weekly Full System Snapshot - 2026-10-24_0400',
                        'Daily Infrastructure Sync - 2026-10-23_2359',
                        'Pre-Update Auto Backup - 2026-10-22_1402',
                      ]
                          .map((value) => DropdownMenuItem(
                                value: value,
                                child: Text(value,
                                    overflow: TextOverflow.ellipsis),
                              ))
                          .toList(),
                      onChanged: (value) => setState(() => _archive = value!),
                    ),
                    const SizedBox(height: 6),
                    const Text(
                      'Archive size: 4.2 GB. Generated by System Admin.',
                      style: TextStyle(fontSize: 10, color: textMuted),
                    ),
                    const SizedBox(height: 18),
                    const Text('Export Format',
                        style: TextStyle(
                            fontSize: 11, fontWeight: FontWeight.w800)),
                    const SizedBox(height: 8),
                    Wrap(
                      spacing: 10,
                      runSpacing: 10,
                      children: [
                        for (final format in ['ZIP', 'TAR.GZ'])
                          ChoiceChip(
                            label: Text(format),
                            selected: _format == format,
                            selectedColor: primarySoft,
                            onSelected: (_) => setState(() => _format = format),
                          ),
                        Container(
                          padding: const EdgeInsets.only(left: 12),
                          decoration: BoxDecoration(
                            color: modalControlFill,
                            borderRadius: BorderRadius.circular(8),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            children: [
                              const Text('Encrypt Archive',
                                  style: TextStyle(fontSize: 11)),
                              Switch(
                                value: _encrypt,
                                onChanged: (value) =>
                                    setState(() => _encrypt = value),
                              ),
                            ],
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 18),
                    Container(
                      padding: const EdgeInsets.all(12),
                      decoration: BoxDecoration(
                        color: alertSoft,
                        borderRadius: BorderRadius.circular(8),
                      ),
                      child: const Row(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Icon(Icons.shield_outlined, color: alert, size: 18),
                          SizedBox(width: 10),
                          Expanded(
                            child: Text(
                              'Data Governance Policy\nThis export will be logged in the system audit trail. Ensure compliance with regional data privacy regulations.',
                              style: TextStyle(fontSize: 10, color: alert),
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
            ),
            Container(
              width: double.infinity,
              height: modalChromeHeight,
              padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
              decoration: modalFooterDecoration,
              child: Row(
                mainAxisAlignment: MainAxisAlignment.end,
                children: [
                  TextButton(
                    onPressed: () => Navigator.of(context).pop(),
                    child: const Text('Cancel'),
                  ),
                  const SizedBox(width: 14),
                  FilledButton(
                    onPressed: () => Navigator.of(context).pop(
                      ArchiveDownload(
                        archive: _archive,
                        format: _format,
                        encrypted: _encrypt,
                      ),
                    ),
                    style: FilledButton.styleFrom(backgroundColor: primary),
                    child: const Text('Download Archive'),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class ArchiveDownload {
  const ArchiveDownload({
    required this.archive,
    required this.format,
    required this.encrypted,
  });

  final String archive;
  final String format;
  final bool encrypted;
}
